// Recipe data — mixed cuisines, PT-BR. Attached to window for cross-script use.
window.RECIPES = [
  {
    id: "feijoada",
    title: "Feijoada Completa",
    cuisine: "Brasileira",
    category: "Prato principal",
    time: 180,
    difficulty: "Difícil",
    servings: 8,
    hue: 24,
    blurb: "O clássico de domingo: feijão-preto encorpado com cortes de porco, servido com arroz, couve e laranja.",
    ingredients: [
      { item: "Feijão-preto", qty: "500 g" },
      { item: "Costelinha de porco", qty: "400 g" },
      { item: "Linguiça calabresa", qty: "300 g" },
      { item: "Carne-seca dessalgada", qty: "300 g" },
      { item: "Bacon em cubos", qty: "150 g" },
      { item: "Cebola picada", qty: "2 unidades" },
      { item: "Alho", qty: "4 dentes" },
      { item: "Folhas de louro", qty: "2 unidades" },
    ],
    steps: [
      "Deixe o feijão de molho na véspera e cozinhe na pressão com as folhas de louro por 30 minutos.",
      "Dessalgue a carne-seca trocando a água algumas vezes; corte todas as carnes em pedaços médios.",
      "Refogue o bacon, junte as carnes e doure bem para selar os sabores.",
      "Acrescente cebola e alho, refogue até dourar e transfira tudo para a panela do feijão.",
      "Cozinhe em fogo baixo por 1 hora, mexendo de vez em quando, até o caldo encorpar.",
      "Sirva com arroz branco, couve refogada, farofa e gomos de laranja.",
    ],
  },
  {
    id: "moqueca",
    title: "Moqueca de Peixe",
    cuisine: "Brasileira",
    category: "Prato principal",
    time: 50,
    difficulty: "Médio",
    servings: 4,
    hue: 16,
    blurb: "Peixe branco cozido lentamente em leite de coco, dendê e pimentões — perfumado e cremoso.",
    ingredients: [
      { item: "Posta de robalo ou badejo", qty: "800 g" },
      { item: "Leite de coco", qty: "400 ml" },
      { item: "Azeite de dendê", qty: "3 colheres" },
      { item: "Pimentão vermelho e amarelo", qty: "1 de cada" },
      { item: "Tomate", qty: "2 unidades" },
      { item: "Cebola", qty: "1 unidade" },
      { item: "Coentro", qty: "1 maço" },
      { item: "Limão", qty: "1 unidade" },
    ],
    steps: [
      "Tempere o peixe com sal, alho e suco de limão; reserve por 20 minutos.",
      "Corte cebola, pimentões e tomate em rodelas finas.",
      "Em uma panela de barro, monte camadas alternando legumes e peixe.",
      "Regue com leite de coco e dendê, polvilhe coentro e tampe.",
      "Cozinhe em fogo médio por 25 minutos, sem mexer, apenas chacoalhando a panela.",
      "Finalize com mais coentro fresco e sirva com arroz e pirão.",
    ],
  },
  {
    id: "risoto-cogumelos",
    title: "Risoto de Cogumelos",
    cuisine: "Italiana",
    category: "Prato principal",
    time: 40,
    difficulty: "Médio",
    servings: 4,
    hue: 38,
    blurb: "Arroz arbóreo cremoso com mix de cogumelos, vinho branco e um toque generoso de parmesão.",
    ingredients: [
      { item: "Arroz arbóreo", qty: "300 g" },
      { item: "Cogumelos variados", qty: "400 g" },
      { item: "Caldo de legumes", qty: "1 litro" },
      { item: "Vinho branco seco", qty: "120 ml" },
      { item: "Cebola", qty: "1 unidade" },
      { item: "Manteiga", qty: "60 g" },
      { item: "Parmesão ralado", qty: "80 g" },
    ],
    steps: [
      "Refogue a cebola na manteiga até ficar translúcida.",
      "Junte o arroz e mexa por 2 minutos até nacarar os grãos.",
      "Adicione o vinho e deixe evaporar o álcool.",
      "Acrescente o caldo quente em conchas, mexendo até cada porção ser absorvida.",
      "Em paralelo, salteie os cogumelos e incorpore ao risoto na metade do cozimento.",
      "Finalize fora do fogo com manteiga gelada e parmesão, mexendo vigorosamente.",
    ],
  },
  {
    id: "lasanha",
    title: "Lasanha à Bolonhesa",
    cuisine: "Italiana",
    category: "Prato principal",
    time: 90,
    difficulty: "Médio",
    servings: 6,
    hue: 8,
    blurb: "Camadas de massa, ragù de carne cozido lentamente e molho branco gratinado no forno.",
    ingredients: [
      { item: "Massa de lasanha", qty: "500 g" },
      { item: "Carne moída", qty: "600 g" },
      { item: "Molho de tomate", qty: "700 g" },
      { item: "Leite", qty: "500 ml" },
      { item: "Manteiga", qty: "40 g" },
      { item: "Farinha de trigo", qty: "40 g" },
      { item: "Mussarela", qty: "300 g" },
      { item: "Parmesão", qty: "100 g" },
    ],
    steps: [
      "Prepare o ragù refogando a carne com cebola e alho, junte o molho de tomate e cozinhe por 40 minutos.",
      "Faça o bechamel derretendo a manteiga, incorporando a farinha e o leite até engrossar.",
      "Cozinhe a massa al dente, se necessário, conforme a embalagem.",
      "Monte camadas: ragù, massa, bechamel e mussarela, repetindo até preencher a travessa.",
      "Cubra com parmesão e leve ao forno a 200°C por 30 minutos.",
      "Deixe descansar 10 minutos antes de cortar para firmar as camadas.",
    ],
  },
  {
    id: "pao-de-queijo",
    title: "Pão de Queijo",
    cuisine: "Brasileira",
    category: "Acompanhamento",
    time: 45,
    difficulty: "Fácil",
    servings: 30,
    hue: 44,
    blurb: "Bolinhas douradas e elásticas de polvilho com queijo — crocantes por fora, macias por dentro.",
    ingredients: [
      { item: "Polvilho azedo", qty: "500 g" },
      { item: "Leite", qty: "250 ml" },
      { item: "Óleo", qty: "120 ml" },
      { item: "Ovos", qty: "3 unidades" },
      { item: "Queijo meia-cura ralado", qty: "300 g" },
      { item: "Sal", qty: "1 colher de chá" },
    ],
    steps: [
      "Ferva o leite com o óleo e o sal e escalde o polvilho, misturando bem.",
      "Deixe amornar e adicione os ovos um a um, sovando a massa.",
      "Incorpore o queijo ralado até obter massa homogênea e maleável.",
      "Modele bolinhas e disponha em assadeira untada, com espaço entre elas.",
      "Asse a 180°C por 25 minutos, até dourarem e crescerem.",
      "Sirva ainda quentinhos, recém-saídos do forno.",
    ],
  },
  {
    id: "ramen",
    title: "Ramen Shoyu",
    cuisine: "Japonesa",
    category: "Prato principal",
    time: 60,
    difficulty: "Médio",
    servings: 2,
    hue: 28,
    blurb: "Caldo aromático de shoyu com macarrão fresco, ovo marinado e cebolinha.",
    ingredients: [
      { item: "Macarrão para ramen", qty: "200 g" },
      { item: "Caldo de galinha", qty: "1 litro" },
      { item: "Shoyu", qty: "80 ml" },
      { item: "Ovos", qty: "2 unidades" },
      { item: "Gengibre", qty: "1 pedaço" },
      { item: "Alho", qty: "3 dentes" },
      { item: "Cebolinha", qty: "a gosto" },
      { item: "Óleo de gergelim", qty: "1 colher" },
    ],
    steps: [
      "Cozinhe os ovos por 6,5 minutos e mergulhe em água gelada; marine no shoyu.",
      "Aqueça o caldo com gengibre e alho amassados por 20 minutos.",
      "Coe o caldo e tempere com shoyu e óleo de gergelim.",
      "Cozinhe o macarrão conforme a embalagem e escorra.",
      "Monte a tigela com o macarrão, o caldo quente e os ovos cortados ao meio.",
      "Finalize com cebolinha picada e sirva imediatamente.",
    ],
  },
  {
    id: "tacos",
    title: "Tacos al Pastor",
    cuisine: "Mexicana",
    category: "Prato principal",
    time: 55,
    difficulty: "Médio",
    servings: 4,
    hue: 12,
    blurb: "Carne suína marinada em achiote e abacaxi, servida em tortilhas com coentro e cebola.",
    ingredients: [
      { item: "Lombo de porco", qty: "700 g" },
      { item: "Abacaxi", qty: "1/2 unidade" },
      { item: "Pasta de achiote", qty: "3 colheres" },
      { item: "Tortilhas de milho", qty: "12 unidades" },
      { item: "Cebola roxa", qty: "1 unidade" },
      { item: "Coentro", qty: "1 maço" },
      { item: "Limão", qty: "2 unidades" },
    ],
    steps: [
      "Marine a carne fatiada com achiote, suco de limão e alho por 2 horas.",
      "Grelhe a carne em fogo alto até dourar e ficar levemente caramelizada.",
      "Grelhe rodelas de abacaxi e pique em cubos pequenos.",
      "Aqueça as tortilhas em uma frigideira seca.",
      "Monte os tacos com a carne, o abacaxi, cebola roxa e coentro.",
      "Sirva com gomos de limão e molho picante à parte.",
    ],
  },
  {
    id: "curry-grao",
    title: "Curry de Grão-de-Bico",
    cuisine: "Indiana",
    category: "Prato principal",
    time: 40,
    difficulty: "Fácil",
    servings: 4,
    hue: 40,
    blurb: "Curry vegetariano reconfortante com leite de coco, tomate e especiarias quentes.",
    ingredients: [
      { item: "Grão-de-bico cozido", qty: "500 g" },
      { item: "Leite de coco", qty: "400 ml" },
      { item: "Tomate", qty: "3 unidades" },
      { item: "Cebola", qty: "1 unidade" },
      { item: "Curry em pó", qty: "2 colheres" },
      { item: "Gengibre", qty: "1 pedaço" },
      { item: "Espinafre", qty: "2 punhados" },
    ],
    steps: [
      "Refogue cebola, alho e gengibre até dourar.",
      "Adicione o curry e toste rapidamente para liberar o aroma.",
      "Junte o tomate picado e cozinhe até desmanchar.",
      "Acrescente o grão-de-bico e o leite de coco; cozinhe por 15 minutos.",
      "Incorpore o espinafre no final, só até murchar.",
      "Sirva com arroz basmati e pão naan.",
    ],
  },
  {
    id: "brigadeiro",
    title: "Brigadeiro Gourmet",
    cuisine: "Brasileira",
    category: "Sobremesa",
    time: 30,
    difficulty: "Fácil",
    servings: 20,
    hue: 20,
    blurb: "O docinho mais querido do Brasil, no ponto certo de enrolar, coberto com chocolate granulado.",
    ingredients: [
      { item: "Leite condensado", qty: "395 g" },
      { item: "Cacau em pó 50%", qty: "3 colheres" },
      { item: "Manteiga", qty: "1 colher" },
      { item: "Creme de leite", qty: "1 colher" },
      { item: "Granulado belga", qty: "para cobrir" },
    ],
    steps: [
      "Em fogo baixo, misture leite condensado, cacau e manteiga.",
      "Mexa sem parar até a massa desgrudar do fundo da panela.",
      "Adicione o creme de leite e cozinhe mais 1 minuto.",
      "Transfira para um prato untado e deixe esfriar completamente.",
      "Enrole bolinhas com as mãos untadas com manteiga.",
      "Passe no granulado e acomode em forminhas.",
    ],
  },
  {
    id: "caprese",
    title: "Salada Caprese",
    cuisine: "Italiana",
    category: "Entrada",
    time: 15,
    difficulty: "Fácil",
    servings: 2,
    hue: 50,
    blurb: "Tomate, mussarela de búfala e manjericão — simplicidade italiana com bom azeite.",
    ingredients: [
      { item: "Tomate maduro", qty: "3 unidades" },
      { item: "Mussarela de búfala", qty: "200 g" },
      { item: "Manjericão fresco", qty: "1 maço" },
      { item: "Azeite extravirgem", qty: "a gosto" },
      { item: "Flor de sal", qty: "a gosto" },
    ],
    steps: [
      "Corte o tomate e a mussarela em fatias de espessura semelhante.",
      "Intercale as fatias em um prato, em leque ou círculo.",
      "Distribua folhas de manjericão entre as fatias.",
      "Regue generosamente com azeite extravirgem.",
      "Finalize com flor de sal e pimenta-do-reino moída na hora.",
    ],
  },
  {
    id: "bobo",
    title: "Bobó de Camarão",
    cuisine: "Brasileira",
    category: "Prato principal",
    time: 70,
    difficulty: "Médio",
    servings: 6,
    hue: 18,
    blurb: "Creme aveludado de mandioca com camarões, leite de coco e dendê — pura Bahia no prato.",
    ingredients: [
      { item: "Camarão limpo", qty: "800 g" },
      { item: "Mandioca", qty: "1 kg" },
      { item: "Leite de coco", qty: "400 ml" },
      { item: "Azeite de dendê", qty: "3 colheres" },
      { item: "Pimentão", qty: "1 unidade" },
      { item: "Tomate", qty: "2 unidades" },
      { item: "Coentro", qty: "1 maço" },
    ],
    steps: [
      "Cozinhe a mandioca até ficar bem macia e bata com parte do leite de coco.",
      "Tempere os camarões com sal, alho e limão.",
      "Refogue cebola, pimentão e tomate; junte os camarões e doure rapidamente.",
      "Incorpore o creme de mandioca e o restante do leite de coco.",
      "Cozinhe em fogo baixo até encorpar, mexendo sempre.",
      "Finalize com dendê e coentro; sirva com arroz branco.",
    ],
  },
  {
    id: "tiramisu",
    title: "Tiramisù",
    cuisine: "Italiana",
    category: "Sobremesa",
    time: 30,
    difficulty: "Médio",
    servings: 8,
    hue: 34,
    blurb: "Camadas de biscoito embebido em café e creme de mascarpone, polvilhadas com cacau.",
    ingredients: [
      { item: "Biscoito champagne", qty: "300 g" },
      { item: "Mascarpone", qty: "500 g" },
      { item: "Ovos", qty: "4 unidades" },
      { item: "Açúcar", qty: "100 g" },
      { item: "Café espresso forte", qty: "300 ml" },
      { item: "Cacau em pó", qty: "para polvilhar" },
    ],
    steps: [
      "Bata as gemas com o açúcar até esbranquiçar e incorpore o mascarpone.",
      "Bata as claras em neve e adicione delicadamente ao creme.",
      "Mergulhe rapidamente os biscoitos no café frio.",
      "Monte camadas de biscoito e creme em um refratário.",
      "Leve à geladeira por no mínimo 4 horas.",
      "Polvilhe cacau em pó generosamente antes de servir.",
    ],
  },
];

window.CUISINES = ["Brasileira", "Italiana", "Japonesa", "Mexicana", "Indiana"];
window.CATEGORIES = ["Prato principal", "Entrada", "Acompanhamento", "Sobremesa"];
